version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Building project..."
      - echo "Copying template for deployment"
      - cp template.yaml output-template.yaml
artifacts:
  files:
    - output-template.yaml
