version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building project..."
      # If you had a build step like Webpack or TypeScript, add it here
      - echo "Build completed!"

artifacts:
  files:
    - template.yaml
    - src/**        # Include everything inside src folder
    - package.json  # Optional: if needed for deployment
