version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Build stage started"
      - echo "Nothing to build, just preparing artifacts"

artifacts:
  files:
    - '**/*'
