version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the project..."
      - echo "Packaging CloudFormation template"
      - aws cloudformation package --template-file template.yaml --s3-bucket cicd-artifacts-150297827048 --output-template-file output-template.yaml
artifacts:
  files:
    - output-template.yaml
