version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  pre_build:
    commands:
      - echo "Preparing build..."
  build:
    commands:
      - echo "Build stage started"
      - echo "Nothing to build, just preparing artifacts"
  post_build:
    commands:
      - echo "Post-build steps complete"

artifacts:
  files:
    - template.yaml   # 👈 this makes sure the file is available to CloudFormation
