version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building project..."
      - cp template.yaml template.yaml

artifacts:
  files:
    - template.yaml
