AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Pipeline for My App

Parameters:
  GitHubRepo:
    Type: String
    Default: "richiesure/my-app"
  GitHubBranch:
    Type: String
    Default: "main"
  GitHubSecretName:
    Type: String
    Default: "github/MyGitHubToken"

Resources:
  CodePipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cicd-artifacts-150297827048

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::150297827048:role/CodePipelineDeploymentRole
      ArtifactStore:
        Type: S3
        Location: cicd-artifacts-150297827048
        EncryptionKey:
          Id: arn:aws:kms:eu-west-2:150297827048:key/3bb8e03f-8372-4e2f-bfbf-4aafaad8dc39
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: arn:aws:codestar-connections:eu-west-2:150297827048:connection/REPLACE_WITH_CONNECTION_ID
                FullRepositoryId: "richiesure/my-app"
                BranchName: "main"

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: MyAppBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyAppStack
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: arn:aws:iam::150297827048:role/ProdDeploymentRole

Outputs:
  PipelineName:
    Value: !Ref CodePipeline
    Description: The name of the created pipeline
