AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for CI/CD pipeline for my-app

Resources:
  # ----------------------
  # CodeBuild Project
  # ----------------------
  MyAppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MyAppCodeBuild
      ServiceRole: arn:aws:iam::150297827048:role/CodePipelineDeploymentRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  # ----------------------
  # CodePipeline
  # ----------------------
  MyAppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyAppPipeline
      RoleArn: arn:aws:iam::150297827048:role/CodePipelineDeploymentRole
      ArtifactStore:
        Type: S3
        Location: cicd-artifacts-150297827048
      Stages:
        # -------- Source Stage --------
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: arn:aws:codeconnections:eu-west-2:150297827048:connection/2a8a5326-5267-482d-a70b-3d9e3a4a6204
                FullRepositoryId: richiesure/my-app
                BranchName: main
              OutputArtifacts:
                - Name: SourceOutput

        # -------- Build Stage --------
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: MyAppCodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput

        # -------- Deploy Stage --------
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyAppStack
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildOutput::template.yaml
              InputArtifacts:
                - Name: BuildOutput

Outputs:
  PipelineName:
    Description: "The name of the created pipeline"
    Value: !Ref MyAppPipeline

  CodeBuildProjectName:
    Description: "The name of the CodeBuild project"
    Value: !Ref MyAppCodeBuildProject
