AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyAppPipeline
      RoleArn: arn:aws:iam::150297827048:role/ProdDeploymentRole
      ArtifactStore:
        Type: S3
        Location: cicd-artifacts-150297827048
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: MyAppRepo
                BranchName: main
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: MyAppCodeBuildProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyAppDeploymentStack
                TemplatePath: BuildOutput::template.yaml   # ✅ Correct double-colon
                Capabilities: CAPABILITY_IAM
                RoleArn: arn:aws:iam::150297827048:role/ProdDeploymentRole
              RunOrder: 1
