AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for CI/CD Pipeline

Resources:
  # We will define CodePipeline, CodeBuild, CodeDeploy here later
AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Pipeline for Node.js App (Efemena Isaac)

Resources:
  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::150297827048:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: cicd-artifacts-150297827048
        EncryptionKey:
          Id: arn:aws:kms:eu-west-2:150297827048:key/3bb8e03f-8372-4e2f-bfbf-4aafaad8dc39
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: EfemenaIsaac
                Repo: my-app
                Branch: main
                OAuthToken: !Sub "{{resolve:secretsmanager:GitHubTokenSecret:SecretString:token}}"
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: my-app-build
        - Name: DeployPreProd
          Actions:
            - Name: DeployPreProdAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName: my-app-preprod
                DeploymentGroupName: preprod-group
        - Name: DeployProd
          Actions:
            - Name: DeployProdAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                StackName: prod-stack
                Capabilities: CAPABILITY_IAM
                RoleArn: arn:aws:iam::150297827048:role/ProdDeploymentRole
